/* Textos de las insignias nuevas en los 12 idiomas de la app.
   Uso: bt(locale, "clave"). Si falta el idioma o la clave, cae a inglés. */
const D = {
  en: {
    worldLap: "World lap", worldLapDesc: "Each lap = 40,075 km",
    moon1: "Trip to the Moon", moon2: "Round trip to the Moon", moonDesc: "384,400 km each way",
    contComplete: "Continent completed", contCompleteDesc: "Every country of a continent visited",
    crossing: "Boat crossing", crossingDesc: "Trips made by boat",
    streak: "months in a row", streakDesc: "Consecutive months with a trip",
    everyMonth: "Every month", everyMonthDesc: "A trip in each of the 12 months of a year",
    twoCont: "2 continents, 1 day", twoContDesc: "Two continents on the same date",
    arctic: "Arctic Circle", arcticDesc: "A city above 66.5° N",
    hemis: "Both hemispheres", hemisDesc: "Cities in the north and the south",
  },
  es: {
    worldLap: "Vuelta al mundo", worldLapDesc: "Cada vuelta = 40.075 km",
    moon1: "Ida a la Luna", moon2: "Ida y vuelta a la Luna", moonDesc: "384.400 km por trayecto",
    contComplete: "Continente completo", contCompleteDesc: "Todos los países de un continente",
    crossing: "Travesía en barco", crossingDesc: "Viajes realizados en barco",
    streak: "meses seguidos", streakDesc: "Meses consecutivos con algún viaje",
    everyMonth: "Cada mes del año", everyMonthDesc: "Un viaje en cada uno de los 12 meses de un año",
    twoCont: "2 continentes, 1 día", twoContDesc: "Dos continentes en la misma fecha",
    arctic: "Círculo Polar Ártico", arcticDesc: "Una ciudad por encima de 66,5° N",
    hemis: "Ambos hemisferios", hemisDesc: "Ciudades en el norte y en el sur",
  },
  fr: {
    worldLap: "Tour du monde", worldLapDesc: "Chaque tour = 40 075 km",
    moon1: "Voyage vers la Lune", moon2: "Aller-retour vers la Lune", moonDesc: "384 400 km par trajet",
    contComplete: "Continent complété", contCompleteDesc: "Tous les pays d'un continent",
    crossing: "Traversée en bateau", crossingDesc: "Voyages effectués en bateau",
    streak: "mois d'affilée", streakDesc: "Mois consécutifs avec un voyage",
    everyMonth: "Chaque mois", everyMonthDesc: "Un voyage chaque mois de l'année",
    twoCont: "2 continents, 1 jour", twoContDesc: "Deux continents à la même date",
    arctic: "Cercle polaire arctique", arcticDesc: "Une ville au-dessus de 66,5° N",
    hemis: "Deux hémisphères", hemisDesc: "Des villes au nord et au sud",
  },
  de: {
    worldLap: "Weltumrundung", worldLapDesc: "Jede Runde = 40.075 km",
    moon1: "Reise zum Mond", moon2: "Hin und zurück zum Mond", moonDesc: "384.400 km pro Strecke",
    contComplete: "Kontinent komplett", contCompleteDesc: "Alle Länder eines Kontinents",
    crossing: "Schiffsüberfahrt", crossingDesc: "Reisen per Schiff",
    streak: "Monate in Folge", streakDesc: "Aufeinanderfolgende Monate mit Reise",
    everyMonth: "Jeder Monat", everyMonthDesc: "Eine Reise in jedem der 12 Monate eines Jahres",
    twoCont: "2 Kontinente, 1 Tag", twoContDesc: "Zwei Kontinente am selben Datum",
    arctic: "Nördlicher Polarkreis", arcticDesc: "Eine Stadt nördlich von 66,5° N",
    hemis: "Beide Hemisphären", hemisDesc: "Städte im Norden und im Süden",
  },
  pt: {
    worldLap: "Volta ao mundo", worldLapDesc: "Cada volta = 40.075 km",
    moon1: "Viagem à Lua", moon2: "Ida e volta à Lua", moonDesc: "384.400 km por trajeto",
    contComplete: "Continente completo", contCompleteDesc: "Todos os países de um continente",
    crossing: "Travessia de barco", crossingDesc: "Viagens feitas de barco",
    streak: "meses seguidos", streakDesc: "Meses consecutivos com viagem",
    everyMonth: "Todos os meses", everyMonthDesc: "Uma viagem em cada um dos 12 meses de um ano",
    twoCont: "2 continentes, 1 dia", twoContDesc: "Dois continentes na mesma data",
    arctic: "Círculo Polar Ártico", arcticDesc: "Uma cidade acima de 66,5° N",
    hemis: "Ambos os hemisférios", hemisDesc: "Cidades no norte e no sul",
  },
  it: {
    worldLap: "Giro del mondo", worldLapDesc: "Ogni giro = 40.075 km",
    moon1: "Viaggio sulla Luna", moon2: "Andata e ritorno sulla Luna", moonDesc: "384.400 km per tratta",
    contComplete: "Continente completo", contCompleteDesc: "Tutti i paesi di un continente",
    crossing: "Traversata in nave", crossingDesc: "Viaggi fatti in nave",
    streak: "mesi di fila", streakDesc: "Mesi consecutivi con un viaggio",
    everyMonth: "Ogni mese", everyMonthDesc: "Un viaggio in ciascuno dei 12 mesi di un anno",
    twoCont: "2 continenti, 1 giorno", twoContDesc: "Due continenti nella stessa data",
    arctic: "Circolo polare artico", arcticDesc: "Una città oltre 66,5° N",
    hemis: "Entrambi gli emisferi", hemisDesc: "Città a nord e a sud",
  },
  zh: {
    worldLap: "环球旅行", worldLapDesc: "每圈 = 40,075 公里",
    moon1: "登月之旅", moon2: "往返月球", moonDesc: "单程 384,400 公里",
    contComplete: "完成一个大洲", contCompleteDesc: "游遍一个大洲的所有国家",
    crossing: "乘船跨越", crossingDesc: "乘船出行的次数",
    streak: "个月连续", streakDesc: "连续数月都有旅行",
    everyMonth: "每个月", everyMonthDesc: "一年中 12 个月各有一次旅行",
    twoCont: "一天两大洲", twoContDesc: "同一天到达两个大洲",
    arctic: "北极圈", arcticDesc: "北纬 66.5° 以北的城市",
    hemis: "南北半球", hemisDesc: "北半球和南半球都去过城市",
  },
  ja: {
    worldLap: "世界一周", worldLapDesc: "1周 = 40,075 km",
    moon1: "月への旅", moon2: "月への往復", moonDesc: "片道 384,400 km",
    contComplete: "大陸を制覇", contCompleteDesc: "ある大陸のすべての国を訪問",
    crossing: "船の旅", crossingDesc: "船で行った旅",
    streak: "か月連続", streakDesc: "旅行をした月が連続",
    everyMonth: "毎月旅行", everyMonthDesc: "1年の12か月すべてに旅行",
    twoCont: "1日で2大陸", twoContDesc: "同じ日に2つの大陸",
    arctic: "北極圏", arcticDesc: "北緯66.5°より北の都市",
    hemis: "南北両半球", hemisDesc: "北半球と南半球の都市",
  },
  hi: {
    worldLap: "विश्व परिक्रमा", worldLapDesc: "हर चक्कर = 40,075 किमी",
    moon1: "चाँद की यात्रा", moon2: "चाँद की आना-जाना यात्रा", moonDesc: "एक तरफ़ 384,400 किमी",
    contComplete: "महाद्वीप पूरा", contCompleteDesc: "एक महाद्वीप के सभी देश",
    crossing: "जहाज़ से यात्रा", crossingDesc: "जहाज़ से की गई यात्राएँ",
    streak: "महीने लगातार", streakDesc: "यात्रा वाले लगातार महीने",
    everyMonth: "हर महीने", everyMonthDesc: "एक साल के सभी 12 महीनों में यात्रा",
    twoCont: "2 महाद्वीप, 1 दिन", twoContDesc: "एक ही तारीख़ को दो महाद्वीप",
    arctic: "आर्कटिक वृत्त", arcticDesc: "66.5° उत्तर से ऊपर का शहर",
    hemis: "दोनों गोलार्द्ध", hemisDesc: "उत्तर और दक्षिण के शहर",
  },
  ar: {
    worldLap: "حول العالم", worldLapDesc: "كل لفة = 40,075 كم",
    moon1: "رحلة إلى القمر", moon2: "ذهاب وعودة إلى القمر", moonDesc: "384,400 كم في الاتجاه الواحد",
    contComplete: "قارة مكتملة", contCompleteDesc: "كل دول القارة",
    crossing: "عبور بحري", crossingDesc: "رحلات بالسفينة",
    streak: "أشهر متتالية", streakDesc: "أشهر متتالية فيها رحلة",
    everyMonth: "كل شهر", everyMonthDesc: "رحلة في كل شهر من أشهر السنة الـ12",
    twoCont: "قارتان في يوم", twoContDesc: "قارتان في التاريخ نفسه",
    arctic: "الدائرة القطبية الشمالية", arcticDesc: "مدينة فوق 66.5° شمالًا",
    hemis: "نصفا الكرة", hemisDesc: "مدن في الشمال والجنوب",
  },
  ru: {
    worldLap: "Кругосветка", worldLapDesc: "Каждый круг = 40 075 км",
    moon1: "Путь на Луну", moon2: "Туда и обратно на Луну", moonDesc: "384 400 км в одну сторону",
    contComplete: "Континент пройден", contCompleteDesc: "Все страны континента",
    crossing: "Морской переход", crossingDesc: "Поездки на корабле",
    streak: "мес. подряд", streakDesc: "Месяцы подряд с поездкой",
    everyMonth: "Каждый месяц", everyMonthDesc: "Поездка в каждый из 12 месяцев года",
    twoCont: "2 континента за день", twoContDesc: "Два континента в одну дату",
    arctic: "Полярный круг", arcticDesc: "Город севернее 66,5° с. ш.",
    hemis: "Оба полушария", hemisDesc: "Города на севере и на юге",
  },
  ko: {
    worldLap: "세계 일주", worldLapDesc: "1바퀴 = 40,075 km",
    moon1: "달 여행", moon2: "달 왕복", moonDesc: "편도 384,400 km",
    contComplete: "대륙 완주", contCompleteDesc: "한 대륙의 모든 나라",
    crossing: "배 횡단", crossingDesc: "배로 한 여행",
    streak: "개월 연속", streakDesc: "여행한 달이 연속",
    everyMonth: "매달 여행", everyMonthDesc: "한 해 12개월 모두 여행",
    twoCont: "하루에 2개 대륙", twoContDesc: "같은 날짜에 두 대륙",
    arctic: "북극권", arcticDesc: "북위 66.5° 위의 도시",
    hemis: "남북 반구", hemisDesc: "북반구와 남반구의 도시",
  },
};

export function bt(locale, key) {
  const lang = String(locale || "en").toLowerCase().split(/[-_]/)[0];
  return (D[lang] && D[lang][key]) || D.en[key] || key;
}
